name: CodeReview
on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: write
jobs:
  codereview:
    name: Reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Setup Code
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile

      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          brakeman_version: gemfile

      - name: fasterer
        uses: vk26/action-fasterer@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
